"""pivot_career_intelligence

Revision ID: 04693332ea03
Revises: d5e6edbcbdef
Create Date: 2026-05-23 12:04:03.388412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04693332ea03'
down_revision: Union[str, None] = 'd5e6edbcbdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('academic_terms')
    op.execute("UPDATE skill_taxonomy SET skill_type = CASE WHEN parent_id IS NOT NULL THEN 'tool' ELSE 'concept' END WHERE skill_type IS NULL")
    op.alter_column('skill_taxonomy', 'skill_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('skill_taxonomy_skill_name_key', 'skill_taxonomy', type_='unique')
    op.create_index(op.f('ix_skill_taxonomy_skill_name'), 'skill_taxonomy', ['skill_name'], unique=True)
    op.add_column('student_skills', sa.Column('resume_weight', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('student_skills', 'behavior_weight')
    op.drop_column('student_skills', 'academic_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_skills', sa.Column('academic_weight', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('student_skills', sa.Column('behavior_weight', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.drop_column('student_skills', 'resume_weight')
    op.drop_index(op.f('ix_skill_taxonomy_skill_name'), table_name='skill_taxonomy')
    op.create_unique_constraint('skill_taxonomy_skill_name_key', 'skill_taxonomy', ['skill_name'])
    op.alter_column('skill_taxonomy', 'skill_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('term_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marks', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('pass_fail', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('total_marks', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], name='subjects_term_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey')
    )
    op.create_table('academic_terms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gpa', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='academic_terms_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='academic_terms_pkey'),
    sa.UniqueConstraint('user_id', 'semester', 'year', name='uq_user_semester_year')
    )
    # ### end Alembic commands ###
