"""Refactor SkillTaxonomy and StudentSkill for Phase 4

Revision ID: 0e90b7713491
Revises: 2747807100c1
Create Date: 2026-05-12 11:43:05.018194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e90b7713491'
down_revision: Union[str, None] = '2747807100c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_taxonomy', sa.Column('skill_type', sa.String(length=20), nullable=True))
    op.add_column('skill_taxonomy', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'skill_taxonomy', 'skill_taxonomy', ['parent_id'], ['id'])
    op.add_column('student_skills', sa.Column('interview_weight', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('student_skills', sa.Column('communication_weight', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_skills', 'communication_weight')
    op.drop_column('student_skills', 'interview_weight')
    op.drop_constraint(None, 'skill_taxonomy', type_='foreignkey')
    op.drop_column('skill_taxonomy', 'parent_id')
    op.drop_column('skill_taxonomy', 'skill_type')
    # ### end Alembic commands ###
