"""Add high_potential_skills to SkillGap

Revision ID: 2747807100c1
Revises: 7221cc4c8dee
Create Date: 2026-05-12 11:38:46.884594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2747807100c1'
down_revision: Union[str, None] = '7221cc4c8dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gaps', sa.Column('high_potential_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gaps', 'high_potential_skills')
    # ### end Alembic commands ###
