"""add_depth_verified_to_projects

Revision ID: 353ba9408210
Revises: 7f8e9d0c1b2a
Create Date: 2026-07-09 12:54:47.692988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353ba9408210'
down_revision: Union[str, None] = '7f8e9d0c1b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'interview_sessions', 'student_projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('student_projects', sa.Column('depth_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('student_projects', sa.Column('depth_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_projects', 'depth_verified_at')
    op.drop_column('student_projects', 'depth_verified')
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'project_id')
    # ### end Alembic commands ###
