"""add associated_skill_id to roadmap_tasks

Revision ID: 4a0e9fc1107b
Revises: a1b2c3d4e5f6
Create Date: 2026-08-20 01:23:44.081411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a0e9fc1107b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_tasks', sa.Column('associated_skill_id', sa.UUID(), nullable=True))
    op.add_column('roadmap_tasks', sa.Column('submission_link', sa.String(length=500), nullable=True))
    op.add_column('roadmap_tasks', sa.Column('validation_status', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'roadmap_tasks', 'skill_taxonomy', ['associated_skill_id'], ['id'])
    op.add_column('student_projects', sa.Column('repo_url', sa.String(length=255), nullable=True))
    op.add_column('student_projects', sa.Column('extracted_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('student_projects', sa.Column('calculated_complexity', sa.Integer(), nullable=True))
    op.add_column('student_projects', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_projects', 'analyzed_at')
    op.drop_column('student_projects', 'calculated_complexity')
    op.drop_column('student_projects', 'extracted_skills')
    op.drop_column('student_projects', 'repo_url')
    op.drop_constraint(None, 'roadmap_tasks', type_='foreignkey')
    op.drop_column('roadmap_tasks', 'validation_status')
    op.drop_column('roadmap_tasks', 'submission_link')
    op.drop_column('roadmap_tasks', 'associated_skill_id')
    # ### end Alembic commands ###
