"""add_learning_resources

Revision ID: 4f15d3899166
Revises: 04693332ea03
Create Date: 2026-07-06 00:44:22.413233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f15d3899166'
down_revision: Union[str, None] = '04693332ea03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('resource_url', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('roadmap_tasks', sa.Column('resource_source', sa.String(length=20), nullable=True))
    op.add_column('roadmap_tasks', sa.Column('learning_resource_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'roadmap_tasks', 'learning_resources', ['learning_resource_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmap_tasks', type_='foreignkey')
    op.drop_column('roadmap_tasks', 'learning_resource_id')
    op.drop_column('roadmap_tasks', 'resource_source')
    op.drop_table('learning_resources')
    # ### end Alembic commands ###
