"""Add skill_resources table

Revision ID: 7221cc4c8dee
Revises: d7682d89e127
Create Date: 2026-04-06 00:38:53.507613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7221cc4c8dee'
down_revision: Union[str, None] = 'd7682d89e127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('resource_url', sa.String(length=500), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_resources')
    # ### end Alembic commands ###
