"""Add role to user

Revision ID: d5e6edbcbdef
Revises: 0e90b7713491
Create Date: 2026-05-17 21:40:51.322332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e6edbcbdef'
down_revision: Union[str, None] = '0e90b7713491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('student', 'admin', 'faculty', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default='student'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role_enum = sa.Enum('student', 'admin', 'faculty', name='userrole')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
